version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongodb_data:/data/db   
    networks:
      - mongo-network
    restart: always

volumes:
  mongodb_data:
    driver: local

networks:
  mongo-network:
    driver: bridge
